In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import load_model
from keras.datasets import mnist
from sklearn.metrics import confusion_matrix
import tensorflow as tf
from keras.models import Sequential
from keras.optimizers import Adam
from keras.layers import Conv2D,Flatten,Dense,MaxPooling2D,Dropout,Activation
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
(x_train, y_train), (x_test, y_test)=mnist.load_data()
model = load_model("lenet_model.h5")

rows=28
cols=28
x_train=x_train.reshape(x_train.shape[0],rows,cols,1)
x_test=x_test.reshape(x_test.shape[0],rows,cols,1)

input_shape=(rows,cols,1)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train / 255.0
x_test = x_test / 255.0

y_train=to_categorical(y_train,10)
y_test=to_categorical(y_test,10)

#model.compile(loss = "mean_squared_error",optimizer = Adam(), metrics=['accuracy'],)

model.compile(loss = "categorical_crossentropy",optimizer = Adam(), metrics=['accuracy'],)

loss, acc = model.evaluate(x_test, y_test)
print('ACCURACY: ', acc)


10000/10000 [==============================] - 1s 108us/step
ACCURACY:  0.9811999797821045


In [3]:
y_prediction = model.predict_classes(x_test)
y_test_original=np.argmax(y_test,axis=1)
confusion=confusion_matrix(y_true=y_test_original, y_pred=y_prediction)
print(confusion)

[[ 960    1    4    0    2    2    7    3    0    1]
 [   0 1129    1    2    0    0    1    2    0    0]
 [   2    0 1010    2    4    0    2   12    0    0]
 [   0    0   10  983    0    8    0    6    0    3]
 [   1    0    1    0  975    0    1    1    1    2]
 [   3    0    0    4    1  881    2    1    0    0]
 [   3    3    3    0    6    4  938    0    1    0]
 [   0    4   16    0    1    0    0 1006    0    1]
 [   0    1    4    2    5    1    0    2  952    7]
 [   3    0    0    0    8   10    1    6    3  978]]
